[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
]

[tool.setuptools]
packages = ["eppi_text_classification"]


[project]
name = "eppi_text_classification"
version = "0.0.1"
description = "Text classification of papers by titles and abstracts."
authors = [
  { name = "Sam Molyneux" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.11.8"
dependencies = []













[tool.ruff]
extend-include = ["*.ipynb"]
lint.select = ["ALL"]
lint.ignore = ["D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",

    "D203",    #Docstring standards for datascience
    "D212",
    
    "T201",
    "T203",
    
    "COM812",
    "ISC001",

    "RET504", #Disables unessecary assignement before return

    "S106", #Checks for harcoded passwords in code

    "N803", #Checks if function parameters are lower caes

    #Maybe enable these for production
    "C408", #Dont use dict()
    "ANN201", #Return type for a function
    "ANN001", #Type for a function paramter
    "PD901" #Generic use of df
    ]
show-fixes = true

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
strict = true
