name: eppi-text-classification-env 
channels:
  - conda-forge 
dependencies:
  - python=3.11.8
  - pip=24.0
  - pip:
    - git+https://github.com/samjmolyneux/eppi-text-classification.git@dev
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
