$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: find_single_model_for_classifier_workbench_pipeline
display_name: Find_single_model_for_eppi_classifier_workbench_pipeline_wrapper
type: pipeline
description: >
  Pipeline wrapper that simply runs the
  `find_single_model_for_classifier_workbench` command component and exposes
  every parameter of that component as a pipeline-level input.

inputs:
  labelled_data_path:
    type: string
  unlabelled_data_path:
    type: string
  title_header:
    type: string
    default: PaperTitle
  abstract_header:
    type: string
    default: Abstract
  label_header:
    type: string
    default: Label
  positive_class_value:
    type: string
    default: "1"
  model_name:
    type: string
  hparam_search_ranges_path:
    type: string
    optional: true
  max_n_search_iterations:
    type: integer
    optional: true
  nfolds:
    type: integer
    default: 3
  num_cv_repeats:
    type: integer
    default: 1
  timeout:
    type: integer
    default: 86400
  use_early_terminator:
    type: boolean
    default: false
  max_stagnation_iterations:
    type: integer
    optional: true
  wilcoxon_trial_pruner_threshold:
    type: number
    optional: true
  use_worse_than_first_two_pruner:
    type: boolean
    default: false
  shap_num_display:
    type: integer
    default: 20
  working_container_url:
    type: string
    default: "https://eppidev2985087618.blob.core.windows.net/sams-prod-simulation"
  output_container_path:
    type: string
  managed_identity_client_id:
    type: string
    default: "df5b7af0-a55a-44d9-9ec7-9cde9abf3051"

jobs:
  find_single_model:
    type: command
    component: azureml://registries/eppi-shared-assets/components/find_single_model_for_classifier_workbench
    inputs:
      labelled_data_path: ${{parent.inputs.labelled_data_path}}
      unlabelled_data_path: ${{parent.inputs.unlabelled_data_path}}
      title_header: ${{parent.inputs.title_header}}
      abstract_header: ${{parent.inputs.abstract_header}}
      label_header: ${{parent.inputs.label_header}}
      positive_class_value: ${{parent.inputs.positive_class_value}}
      model_name: ${{parent.inputs.model_name}}
      hparam_search_ranges_path: ${{parent.inputs.hparam_search_ranges_path}}
      max_n_search_iterations: ${{parent.inputs.max_n_search_iterations}}
      nfolds: ${{parent.inputs.nfolds}}
      num_cv_repeats: ${{parent.inputs.num_cv_repeats}}
      timeout: ${{parent.inputs.timeout}}
      use_early_terminator: ${{parent.inputs.use_early_terminator}}
      max_stagnation_iterations: ${{parent.inputs.max_stagnation_iterations}}
      wilcoxon_trial_pruner_threshold: ${{parent.inputs.wilcoxon_trial_pruner_threshold}}
      use_worse_than_first_two_pruner: ${{parent.inputs.use_worse_than_first_two_pruner}}
      shap_num_display: ${{parent.inputs.shap_num_display}}
      working_container_url: ${{parent.inputs.working_container_url}}
      output_container_path: ${{parent.inputs.output_container_path}}
      managed_identity_client_id: ${{parent.inputs.managed_identity_client_id}}
