name: Diagnose Windows

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Debug and Fix
      run: |
        echo "TEMP: ${{ runner.temp }}"
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "RUNNER_WORKSPACE: ${{ runner.workspace }}"
        echo "SYSTEMROOT: $SYSTEMROOT"
             
        python -m pip install --upgrade pip
        pip install .
      env:
        # Ensure TEMP and TMP are on the same filesystem as the workspace
        TEMP: ${{ github.workspace }}\temp
        TMP: ${{ github.workspace }}\temp
        TMPDIR: ${{ github.workspace }}\temp

    - name: Create temporary directory
      run: |
        mkdir ${{ github.workspace }}\temp