name: Diagnose Windows

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      id: su-py
      with:
        python-version: '3.11'
    
    - name:
      run: |
        echo "The python-path is ${{ steps.su-py.outputs.python-location }}"
        
    - name: Check where Python
      run: where python
  
    - name: Install dependencies with pinned version
      run: |
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "RUNNER_WORKSPACE: ${{ runner.workspace }}"
        python -m pip install . 
    #   env:
    #     TEMP: C:\temp
    #     TMP: C:\temp
    #     pythonLocation: C:\hostedtoolcache\windows\Python\3.11.9\x64
