name: Generate Directory Structure

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  generate-directory-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for added or deleted files
        run: |
          # Check if any files were added or deleted
          if git diff --name-status HEAD^ | grep -E '^(A|D)'; then
            echo "Files added or deleted. Proceeding with directory structure update."
          else
            echo "No files added or deleted. Exiting."
            exit 0
          fi

      - name: Generate directory structure
        run: |
          echo '```' >> DIRECTORY_STRUCTURE.md
          tree -I '.git|.github|DIRECTORY_STRUCTURE.md' --noreport >> DIRECTORY_STRUCTURE.md
          echo '```' >> DIRECTORY_STRUCTURE.md

      - name: Update README.md
        run: |
          # Remove the old directory structure section using sed
          sed -i '/<!-- directory-structure-start -->/,/<!-- directory-structure-end -->/d' README.md

          # Add the new directory structure
          awk '/# Structure/{print;print "<!-- directory-structure-start -->";system("cat DIRECTORY_STRUCTURE.md");print "<!-- directory-structure-end -->";next}1' README.md > README.tmp

          # Clean up
          mv README.tmp README.md
          if [ -f DIRECTORY_STRUCTURE.md ]; then
            rm DIRECTORY_STRUCTURE.md
          fi          
          

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md

          # Check for changes before committing
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m 'Update directory structure in README.md'
          git push

