name: Generate Directory Structure

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  generate-directory-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate directory structure
        run: |
          echo "# Directory Structure" > DIRECTORY_STRUCTURE.md
          echo '```' >> DIRECTORY_STRUCTURE.md
          tree -I '.git|.github' >> DIRECTORY_STRUCTURE.md
          echo '```' >> DIRECTORY_STRUCTURE.md

      - name: Update README.md
        run: |
          # Remove the old directory structure section using sed
          sed -i '/<!-- directory-structure-start -->/,/<!-- directory-structure-end -->/d' README.md

          # Add the new directory structure section
          echo "<!-- directory-structure-start -->" >> README.md
          cat DIRECTORY_STRUCTURE.md >> README.md
          echo "<!-- directory-structure-end -->" >> README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md DIRECTORY_STRUCTURE.md
          git commit -m 'Update directory structure in README.md'
          git push

