name: uv test

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: yezz123/setup-uv@v4
      with: 
        uv-venv: "my_venv"

    - run: |
        uv --version

    - name: Install dependencies
      run: |
        uv pip install .[test]
        uv pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl
    
    - name: Install Spacy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Check correct installation
      run: |
        python tests/check_install.py
    
    - name: Test with Ruff
      run: |
        ruff check eppi_text_classification/
      continue-on-error: true